name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Шаг 3: Раскодирование Base64-секрета
      - name: Decode Base64 Secret
        run: |
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY_BASE64 }}" | base64 --decode > key.json
